@startuml
class NameSorter{
    -ArrayList<String> names;

    +NameSorter()

    +readNamesFromText(String fileName)
    +sortNames()
    +writeNamesAsText(String fileName)
}

class NameReader{
+readNamesFromText(String fileName)

}
@enduml