@startuml
class Solution41{
    -ArrayList<String> names;
    -NameSorter;
}
class NameSorter{

    -vis NameSorter(Scanner, (arrayList)
    -vis printNames(arrayList) : void
}

NameSorter --> Solution41


@enduml